### ISSUE TITLE
UI for 20 April Live Demo

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renga-ui#132]
We are targeting a working demo by early April. We want to demo the following:

0. [slide] Explain terminology
1. [slide] Init a repo with the renga CLI
2. [slide] Add data to the repo
3. Create a project in the UI
4. [slide] Push the local repo to the project
5. Create two kus in the UI: preprocess data; analyze data
6. [slide] Do work on ku 1: apply preprocessing to data. Push results to server
7. [slide - maybe live?] Do work on ku 2:  analyze processed data (in a notebook), done by another person. Push results to server
8. View project in server and see: lineage of preprocessed data; results in notebook
9. Launch notebook on server, modify contents, create a new commit.

Additions: import a data set from another repo; 

# 0 Unified UI Style
We need to decide and standardize on some stylistic issues:
- [x] ~~Tabs~~ or pills for card navigation [Bootstrap Card Nav](http://getbootstrap.com/docs/4.0/components/card/#navigation)

# Projects

- [x] Support creating projects (#129)
- [x] Improve the layout of the projects page ( #141)
- [x] Add ability to set tags for projects
- [x] Display remote URL for projects
- [x] Add ability to star projects (#163)

# Kus

- [x] Improve the layout of the Kus page ( #142)
- [x] Ku properties should be displayed in lists and details page (#113)
- [x] Adding a contribution should give feedback -- the submit button should be disabled until a response comes back, and the page should be updated when the response arrives.
- [x] It should be able to mark a Ku as complete (#172)

# Files

- [x] Show files, grouped by type: data, output, notebook, workflow, misc.
- [x] Lineage of files should be displayed where appropriate (#159)

# Minor UI Improvements

- [ ] Improve styling of Markdown content to be better integrated with UI
- [ ] Improve styling of notebook content to be better integrated with UI
- [x] Show Avatars instead of generic icons for users
